// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
//  import 'firebase_options.dart';
//  // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkP1vXWhZkxbeTF1eV6Itr1fuj9DFh1iI',
    appId: '1:965798040190:web:1017f9cff0cdf736cefe2f',
    messagingSenderId: '965798040190',
    projectId: 'mcoffee-d8ab9',
    authDomain: 'mcoffee-d8ab9.firebaseapp.com',
    storageBucket: 'mcoffee-d8ab9.firebasestorage.app',
    measurementId: 'G-G81QRMVL77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm_uhqMeFJcq4Vi8GvE79mzyhBQ4MM4pQ',
    appId: '1:965798040190:android:bd5db0d4faa6da7acefe2f',
    messagingSenderId: '965798040190',
    projectId: 'mcoffee-d8ab9',
    storageBucket: 'mcoffee-d8ab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOj6a2Xj3ccjoz5dz23azXj0M-8MktvEk',
    appId: '1:965798040190:ios:4416fba7089d304ecefe2f',
    messagingSenderId: '965798040190',
    projectId: 'mcoffee-d8ab9',
    storageBucket: 'mcoffee-d8ab9.firebasestorage.app',
    iosBundleId: 'com.example.mcoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOj6a2Xj3ccjoz5dz23azXj0M-8MktvEk',
    appId: '1:965798040190:ios:4416fba7089d304ecefe2f',
    messagingSenderId: '965798040190',
    projectId: 'mcoffee-d8ab9',
    storageBucket: 'mcoffee-d8ab9.firebasestorage.app',
    iosBundleId: 'com.example.mcoffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkP1vXWhZkxbeTF1eV6Itr1fuj9DFh1iI',
    appId: '1:965798040190:web:750f7fd03928a19dcefe2f',
    messagingSenderId: '965798040190',
    projectId: 'mcoffee-d8ab9',
    authDomain: 'mcoffee-d8ab9.firebaseapp.com',
    storageBucket: 'mcoffee-d8ab9.firebasestorage.app',
    measurementId: 'G-N6W3B2WW1D',
  );
}
